### ISSUE TITLE
unable to recognise column "snpid"

### ISSUE THREAD

**Issue by Xuemin-Wang** [n-mounier/bGWAS#6]
Dear Ninon,

On the usage page, it indicates that multiple types o f SNP-identifier can be used (rs or rsid, snp, snpid, rnpid). However, it seems like bGWAS is unable to recognise snps stored in column "snpid", incidating an error below.
**Error: Column `rs` not found in `.data`**

I also had a look at the help document and found no argument to change the 'rs' column to 'snpid'. 
bGWAS(name, GWAS, Z_matrices = "~/ZMatrices/", prior_studies = NULL,
       MR_threshold = 1e-06, MR_ninstruments = 3, MR_pruning_dist = 500,
       MR_pruning_LD = 0, MR_shrinkage = 1, stepwise_threshold = NULL,
       prior_shrinkage = NULL, sign_method = "p", sign_thresh = 5e-08,
       use_permutations = FALSE, res_pruning_dist = 500,
       res_pruning_LD = 0, save_files = FALSE, verbose = TRUE)

Is this a knows issue? I can update the column name in the ZMatrix, but it will be better for users if you can fix it.

Many thanks,
xuemin

**Comment by Xuemin-Wang** [comment]
Similarly, it cannot recognise columns 'a1' and 'a2' (see logging info below).

...
<<< Identification of significant prior GWASs for MR >>>
> Creating the Z-Matrix of strong instruments
# Loading the ZMatrix...
Selecting studies :
19 studies
490,518 SNPs
# Adding data from the conventional GWAS :
 "allEC_unmunged"
Error: Column `ZMat_alt` not found in `.data`
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning messages:
1: Unknown or uninitialised column: 'alt'.
2: Unknown or uninitialised column: 'ref'.

**Comment by Xuemin-Wang** [comment]
However, these issues were fixed by changing column headers.

**Comment by n-mounier** [comment]
Hello,
Sorry for the late reply. I think something was unclear in the documentation. For the GWAS that is analysed, indeed alternative column names are allowed. But if you are using your own Z-matrix (to create the prior), **specific column names are needed** and described here: https://github.com/n-mounier/bGWAS/blob/master/doc/ZMatrices.md#how-to-use-your-own-data
So think these errors are all due to an incorrect Z-matrix, and indeed the only way to solve them in to change the column names to match the ones that are required, as you did.
